name: isar_inspector
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  clickup_fading_scroll:
    git:
      url: https://github.com/clickup/clickup_fading_scroll
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  isar:
    path: ../isar
  vm_service: ^11.9.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
